### ISSUE TITLE
Options appear to be ignored

### ISSUE THREAD

**Issue by vorburger** [NordcomInc/devcontainer-features#20]
I just wanted to let you know that I've (only very briefly, without doing any further debugging) tried this feature out, for https://github.com/google/android-fhir/issues/2481, and it seems to me that the Options to chose the Android SDK version appear to be ignored?

In https://github.com/google/android-fhir/pull/2482 ([here](https://github.com/google/android-fhir/pull/2482/files#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686R18)) I originally tried:

```
 "ghcr.io/nordcominc/devcontainer-features/android-sdk:1": {
      "platform": "33",
      "build_tools": "33.0.1"
    }
```

and in the `creation.log` it (correctly) noticed:

```
#16 0.762 Feature       : Android SDK2024-03-15 23:05:49.933Z: 
#16 0.762 Description   : Install Android SDK cmdline-, platform-, and, build-tools
#16 0.762 Id            : ghcr.io/nordcominc/devcontainer-features/android-sdk
#16 0.762 Version       : 1.1.0
#16 0.762 Documentation : 
#16 0.762 Options       :
#16 0.762     PLATFORM="33"2024-03-15 23:05:50.082Z: 
#16 0.762     BUILD_TOOLS="33.0.1"
```

but then it still installed v34 instead of v33:

```
[====                                   ] 10% Downloading build-tools_r34-linux.
[=======                                ] 18% Unzipping... android-14/NOTICE.txt
```

I've noticed that several folks published Dev Container Features for installing the Android SDK, so I'll try out another one. I'm only filing this issue to let you know.

**Comment by filiphsps** [comment]
Thanks, looks like a simple shell script mistake managed to slip under the radar. I'll take a look at it over the weekend! :)

**Comment by filiphsps** [comment]
Appears that somebody already had investigated, I'll do a proper check later to verify but it should/might be working now!

**Comment by filiphsps** [comment]
> I just wanted to let you know that I've (only very briefly, without doing any further debugging) tried this feature out, for [google/android-fhir#2481](https://github.com/google/android-fhir/issues/2481), and it seems to me that the Options to chose the Android SDK version appear to be ignored?
> 
> In [google/android-fhir#2482](https://github.com/google/android-fhir/pull/2482) ([here](https://github.com/google/android-fhir/pull/2482/files#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686R18)) I originally tried:
> 
> ```
>  "ghcr.io/nordcominc/devcontainer-features/android-sdk:1": {
>       "platform": "33",
>       "build_tools": "33.0.1"
>     }
> ```
> 
> and in the `creation.log` it (correctly) noticed:
> 
> ```
> #16 0.762 Feature       : Android SDK2024-03-15 23:05:49.933Z: 
> #16 0.762 Description   : Install Android SDK cmdline-, platform-, and, build-tools
> #16 0.762 Id            : ghcr.io/nordcominc/devcontainer-features/android-sdk
> #16 0.762 Version       : 1.1.0
> #16 0.762 Documentation : 
> #16 0.762 Options       :
> #16 0.762     PLATFORM="33"2024-03-15 23:05:50.082Z: 
> #16 0.762     BUILD_TOOLS="33.0.1"
> ```
> 
> but then it still installed v34 instead of v33:
> 
> ```
> [====                                   ] 10% Downloading build-tools_r34-linux.
> [=======                                ] 18% Unzipping... android-14/NOTICE.txt
> ```
> 
> I've noticed that several folks published Dev Container Features for installing the Android SDK, so I'll try out another one. I'm only filing this issue to let you know.


I can confirm that it's working now using the configuration you originally tried with!
![image](https://github.com/NordcomInc/devcontainer-features/assets/108444335/b9754066-a3fc-4ad9-b5ff-b9cbbd42161d)

Sorry about miss there! This devcontainer feature was originally created by me to play a little bit with Compose without having to spin up a full-blown Android environment locally, but there hasn't been too much time available for that, so this ended up mostly lying dormant 😅

Let me know if any other issues arise!
